import profile from "./assets/profile.jpeg";

export const personalData = {
  name: "Muaviya Imran",
  designation: ["Full Stack Developer", "Mobile App Developer"],
  github: "https://github.com/MuaviyaImran",
  linkedIn: "https://www.linkedin.com/in/muaviya-imran-4749a7215/",
  facebook:
    "https://www.facebook.com/profile.php?id=100013990093022&mibextid=ZbWKwL",
  instagram: "https://www.instagram.com/itxx_muaviya/",
  skills: [
    "HTML",
    "CSS",
    "JavaScript",
    "React.js",
    "Next.js",
    "Vue.js",
    "Nuxt.js",
    "Tailwind CSS",
    "SASS",
    "Bootstrap",
    "GSAP",
    "Particle.js",
    "Material UI",
    "Ant Design",
    "Ark UI",
    "Panda CSS",
    "Styled Components",
    "Node.js",
    "Express.js",
    "Golang",
    "Chi",
    "Echo",
    "MongoDB",
    "PostgreSQL",
    "SQL Queries",
    "Flask API",
    "FastAPI",
    "Python",
    "Git",
    "GitHub",
    "Flutter",
    "Strapi",
    "shadcn/ui",
    "TypeScript",
    "Redux Toolkit",
    "Redux",
    "REST APIs",
    "Authentication & Authorization",
    "Selenium",
    "Playwright",
    "Cypress Testing",
    "OpenAI API",
    "LangChain",
    "Anthropic API",
    "LLM Embeddings",
    "AI Model Integration",
    "Data Scraping",
    "Pandas",
    "Firebase",
    "Netlify",
    "Vercel",
    "DigitalOcean Server",
    "GitHub Pages",
    "FormKit",
    "Pinia",
    "Microservices Architecture",
  ],
  email: "muaviyaimran1122@gmail.com",
  phone: "+923249411360",
  address: "Lahore, Pakistan",
};

export const AboutData = {
  name: "Muaviya Imran",
  description:
    "Full-Stack Developer with 2+ years of professional experience delivering scalable, high-quality web applications. Proven expertise in React.js, Vue.js, Next.js, Golang, and Python with strong skills in backend APIs, microservices, and AI integrations (OpenAI, Anthropic, LangChain). Adept at collaborating with international teams, building performant, user-focused solutions, and delivering results that align with business goals.",
  profile: profile,
};

export const experiences = [
  {
    id: 1,
    title: "Frontend Developer (Part-time)",
    company: "Golden Gate Innovations",
    duration: "(Apr 2025 - Present)",
    location: "Remote, US-Based",
    responsibilities: [
      "Developing an e-commerce platform using React.js, Panda CSS, and Ark UI, with end-to-end Cypress testing",
      "Implementing responsive UI components, ensuring cross-browser compatibility, and optimizing for performance",
      "Collaborating remotely with US-based stakeholders, demonstrating adaptability across time zones and cultural contexts",
    ],
  },
  {
    id: 2,
    title: "Associate Software Engineer",
    company: "Datumbrain",
    duration: "(Sep 11, 2023 - Present)",
    location: "Lahore, Pakistan",
    responsibilities: [
      "Full stack development NextJs, Go Framework, Selenium, ReactJs, VueJs and Python ",
      "Performance and optimization of live products",
      "Provide optimal solutions",
    ],
  },
  {
    id: 3,
    title: "MERN Stack intern",
    company: "Shayan Solutions",
    duration: "(Jun 1,2023 - Sep 1, 2023)",
    location: "Lahore, Pakistan",
    responsibilities: [
      "Backend development NextJs Framework",
      "Frontend development with ReactJs, and Tailwind",
      "Performance and optimization of live products",
      "Provide optimal solutions",
    ],
  },
  {
    id: 4,
    title: "Software Engineer",
    company: "Freelance",
    duration: "(Aug 2021 - Present)",
    location: "Lahore, Pakistan",
    responsibilities: [
      "Full stack development NextJs Framework, VueJs, Tailwind and bootstrap",
      "Worked on Flutter mobile applications",
      "Performance and optimization of live products",
      "Provide optimal solutions",
      "Flutter mobile application development",
    ],
  },
  {
    id: 5,
    title: "Salesforce Backend Engineer",
    company: "Systems Limited",
    duration: "(Aug 2021 - Nov 2021)",
    location: "Lahore, Pakistan",
    responsibilities: [
      "Backend development with SFRA architecture",
      "Provide optimal solutions",
      "Performance and optimization of live products",
    ],
  },
];

export const skillsData = [
  "Photoshop",
  "Angular",
  "Next Js",
  "Nuxt Js",
  "Typescript",
  "Vue",
  "Postgresql",
  "Tailwind",
  "ViteJs",
  "Vuetifyjs",
  "C",
  "C++",
  "Dart",
  "Firebase",
  "MaterialUI",
  "Figma",
  "Flutter",
  "Flask",
  "MySQL",
  "ReactJs",
  "Bootstrap",
  "Docker",
  "NodeJs",
  "SAAS",
  "MongoDB",
  "HTML",
  "CSS",
  "Javascript",
  "Git",
  "GCP",
  "office",
  "goLang",
  "strapi",
  "Python",
  "FastAPI",
  "RestAPI",
  "microservices",
  // "c#",
  // "illustrator",
  // "ionic",
  // "Django",
  // "Django Rest Framework",
  // "Elixir",
  // "Phoenix",
  // "AWS",
  // "React Native",
  // "PHP",
  // "Laravel",
  // "DataScience",
  // "redis",
  // "graphql",
  // "jenkins",
  // "ionic",
];

export const projectsData = [
  {
    id: 1,
    name: "Query GPT",
    description:
      "AI-powered analytics platform for TikTok content. Tracks trends, monitors influencer engagement, and uses microservices architecture with ETL, GPT, and chat modules.",
    liveUrl: "",
    role: "Full Stack Developer",
    stack:
      "LangChain, Golang, OpenAI, Python, Selenium, MongoDB, PostgreSQL, Chi, FastAPI",
  },
  {
    id: 2,
    name: "Bidding Extension for Upwork",
    description:
      "Browser extension that scrapes job postings, ranks matches, and auto-generates proposals using large language models.",
    liveUrl: "",
    role: "Full Stack Developer",
    stack: "React.js, Selenium, Anthropic API",
  },
  {
    id: 3,
    name: "Fintech EMI Application",
    description:
      "Electronic Money Institution and Payment Service Provider licensed by the Central Bank of Cyprus. Enhanced platform performance, implemented authentication, and conducted compliance checks for user and admin management.",
    liveUrl: "",
    role: "Frontend Developer",
    stack: "Vue.js, Tailwind CSS, Vite.js, FormKit, Golang, Echo, PostgreSQL",
  },
  {
    id: 4,
    name: "Gett",
    description:
      "Food delivery and grocery app connecting users with local restaurants and stores in the US. Features a user-friendly interface, real-time tracking, and a wide selection of local businesses.",
    liveUrl: "https://www.gett.co/",
    role: "Frontend Developer",
    stack: "React.js, Capacitor.js, Panda CSS, Ark UI",
  },
  {
    id: 5,
    name: "Language Learner / Translator App",
    description:
      "Spanish-to-English language learning and translation tool integrating Google Translate and OpenAI for interactive practice.",
    liveUrl: "",
    role: "Full Stack Developer",
    stack: "React.js, Tailwind CSS, GoLang, OpenAI API",
  },
  // {
  //   id: 4,
  //   name: "Inventory Management System",
  //   description:
  //     "Business inventory solution with role-based authentication, middleware integration, and secure API endpoints.",
  //   liveUrl: "",
  //   role: "Full Stack Developer",
  //   stack: "React.js, Golang, Echo, PostgreSQL",
  // },
  // {
  //   id: 4,
  //   name: "PFFT",
  //   description:
  //     "AI-powered humor generation tool that creates structured headings from user input. Users can click on any heading to instantly expand it into a detailed paragraph, enabling effortless creation of high-quality comedic content.",
  //   liveUrl: "https://pfft.ai/",
  //   role: "Full Stack Developer",
  //   stack: "Next.js, Tailwind CSS",
  // },
  // {
  //   id: 7,
  //   name: "AI Python Models",
  //   description:
  //     "Collection of AI tools including a voice-based mood predictor and an AI solver for Linear Differential Equations.",
  //   liveUrl: "",
  //   role: "Full Stack Developer",
  //   stack: "Next.js, Python, Flask API",
  // },
  // {
  //   id: 8,
  //   name: "Metaland",
  //   description:
  //     "Virtual world platform offering real communication and services in a single space, enabling clients to access multiple services with ease.",
  //   liveUrl: "https://metaland.mn/en/about",
  //   role: "Full Stack Developer",
  //   stack: "MongoDB, Express.js, React.js, Node.js",
  // },
  // {
  //   id: 9,
  //   name: "Neuromise",
  //   description:
  //     "Design studio helping startups, companies, and agencies elevate digital products, branding, and graphic design to world-class standards.",
  //   liveUrl: "https://neuromise.com/",
  //   role: "Frontend Engineer",
  //   stack: "Next.js, Tailwind CSS",
  // },
  // {
  //   id: 10,
  //   name: "Mobile Apps Suite",
  //   description:
  //     "Developed cross-platform mobile apps including a messaging app, blood bank management, online mart, and news feed.",
  //   liveUrl: "",
  //   role: "Mobile App Developer",
  //   stack: "Flutter, Firebase",
  // },
];

export const educations = [
  {
    id: 1,
    title: "Bachelors in Computer Science",
    duration: "2019 - 2023",
    institution: "University of Engineering and Technology, Lahore",
  },
];

export const ContactMe = {
  description:
    "If you have any questions or concerns, please don't hesitate to contact me. I am open to any work opportunities that align with my skills and interests.",
};
